### ISSUE TITLE
Create Heroku app and pipeline to aid UI reviews

### ISSUE THREAD

**Issue by fofr** [alphagov/email-alert-frontend#102]
Email alert frontend needs a Heroku app representing master and a pipeline for reviewing changes to UI and components.

**Comment by fofr** [comment]
When available the link should be added to:
https://docs.publishing.service.gov.uk/manual/components.html#component-guides

**Comment by tijmenb** [comment]
This would need the `Rails.env.production?` requirement to be removed too:

https://github.com/alphagov/email-alert-frontend/blob/db9996c128539031dd7c1a8f97d98098ba51b389/config/routes.rb#L2-L4
