### ISSUE TITLE
GOV.UK Elements conflicting CSS causing padding issues.

### ISSUE THREAD

**Issue by nickcolley** [alphagov/email-alert-frontend#39]
The way GOV.UK Elements styles `#content` conflicts with our styling with the `#wrapper`.

This results in too much padding around the page.

Seems like there may be some similar issues with the custom margins on the expanded inputs too. Would recommend keeping the pattern as described in GOV.UK Elements and trying to update the pattern upstream.

Can reproduce when testing on smaller viewports e.g. mobile, tablet

![screen shot 2017-03-29 at 14 04 58](https://cloud.githubusercontent.com/assets/2445413/24455837/efcbbfea-1488-11e7-9673-ef548f83132c.png)
![screen shot 2017-03-29 at 14 05 08](https://cloud.githubusercontent.com/assets/2445413/24455840/f0b43374-1488-11e7-9396-4213dab96e25.png)

Publishing Frontend Support: https://trello.com/c/SDaspypN/45-gov-uk-elements-conflicting-css-causing-padding-issues

**Comment by nickcolley** [comment]
Related converstation: https://github.com/alphagov/email-alert-frontend/pull/33/files#r108202396

**Comment by tijmenb** [comment]
I've added this issue to the tech debt card: https://trello.com/c/klZnFNZi/70-email-alert-frontend-uses-govuk-elements
