### ISSUE TITLE
Issue moving through app

### ISSUE THREAD

**Issue by chris-gds** [alphagov/email-alert-frontend#913]
There is an issue within this app as it's interacted with using the example page links

Starting 
`http://email-alert-frontend.dev.gov.uk/email-signup?link=%2Fgovernment%2Forganisations%2Fgovernment-digital-service`

As you move through the app the actual URL changes which generates an error page 
`http://www.dev.gov.uk/email/subscriptions/new?topic_id=government-digital-service`

![Screenshot 2020-11-19 at 13 51 45](https://user-images.githubusercontent.com/71266765/99674888-84571200-2a6e-11eb-87ab-1f6aadcc3d23.png)

![Screenshot 2020-11-19 at 13 51 53](https://user-images.githubusercontent.com/71266765/99674902-86b96c00-2a6e-11eb-80fc-c1b47b3b5304.png)

**Comment by kevindew** [comment]
Thanks for raising @chris-gds 

I can see that is rather inconvenient in a dev environment. I had a look into it, hoping it would be an unnecessary absolute redirect that could be changed to relative, however it's a bit of a deeper pain than this. The URL comes from a different service, Email Alert API: https://github.com/alphagov/email-alert-api/blob/1711885b4df9c80aed5d8d2333e4e007c778badd/app/models/subscriber_list.rb#L49 - It'd probably be fine that this is a relative path, but not sure if that'd break things for any clients.
